name: Run GRFolres Tests (Intel)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    env:
      CHOMBO_HOME: ${{ github.workspace }}/Chombo/lib
      OMP_NUM_THREADS: 1
      GRCHOMBO_HOME: ${{ github.workspace }}/GRChombo
      GRCHOMBO_SOURCE: ${{ github.workspace }}/GRChombo/Source

    steps:
    - name: Checkout Chombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/Chombo
        path: Chombo

    - name: Checkout GRChombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/GRChombo
        path: GRChombo

    - name: Checkout ModifiedGravity
      uses: actions/checkout@v2
      with:
        path: ModifiedGravity

    - name: Install Chombo dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install csh libgetopt-complete-perl

    - name: Install Intel compilers/MPI
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        sudo apt-get -y install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2023.2.4 intel-oneapi-compiler-fortran-2023.2.4 intel-oneapi-mkl-2023.2.0 intel-oneapi-mpi intel-oneapi-mpi-devel intel-oneapi-openmp-2023.2.4
      working-directory: /tmp

    - name: Build Chombo
      run: |
        source /opt/intel/oneapi/setvars.sh
        cp $GRCHOMBO_HOME/InstallNotes/MakeDefsLocalExamples/intel-classic-no-hdf5-minimal.Make.defs.local $CHOMBO_HOME/mk/Make.defs.local
        make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools
      working-directory: ${{ env.CHOMBO_HOME }}

    - name: Build GRFolres Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make test -j 4
      working-directory: ${{ github.workspace }}/ModifiedGravity

    - name: Run GRFolres Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make run -j 2
      working-directory: ${{ github.workspace }}/ModifiedGravity
